name: Build Kernel A04s EZE2
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/nestans/android_kernel_a047f_eur
          kernel-branch: sus
          config: exynos850-a04sxx_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r450784d
          ksu: true
          ksu-version: main
