name: Build Kernel A04s EZE2
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/SavedByLight/android_kernel_samsung_a04s
          kernel-branch: main
          config: a047_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          gnd-clang: true
          ksu: true
          ksu-version: main
